os: osx

osx_image: xcode7.1
 
sudo: required

script:
 - export COMPILER=g++-6
 - brew update; brew tap homebrew/science
 - brew install --build-bottle fftw --with-openmp
 - brew bottle fftw
 - export RELEASE_FILE=fftw*.tar.gz
 - echo ${RELEASE_FILE}

deploy:
  provider: releases
  edge:
    branch: releases-fix
  api_key: $github_token
  file: "${RELEASE_FILE}"
  skip_cleanup: true
  overwrite: true

